name: arrowlogo
author: Burak Emir <burak.emir@gmail.com>
dependencies:
  ace: '>= 0.6.2'
  browser: '>=0.10.0+2 <0.11.0'
  angular2: '>= 2.0.0-alpha.26 <2.1.0'
dev_dependencies:
  test: '>= 0.12.3 <0.13.0'

transformers:
  - angular2:
      entry_point: web/arrowlogo.dart # see docs: https://github.com/angular/angular/wiki/Angular-2-Dart-Transformer
  - $dart2js:
      minify: true
      commandLineOptions: [--trust-type-annotations, --trust-primitives, --dump-info]
        # trust-* tells Dart to trust your type annotations and to therefore be able to prune more JS,
        # see: http://dovdev.com/get-the-most-out-of-dart2js-with-a-little-trust/