name: arrowlogo
author: Burak Emir <burak.emir@gmail.com>
description: Web Interpreter for a Logo-like language
dependencies:
  angular: '^5.0.0'
  # migrate to Dart 2
  build_runner: '^0.10.0'
  build_test: '^0.10.2'
  build_web_compilers: '^0.4.0'


dev_dependencies:
  angular_test: '^2.0.0-beta'
  test: '^1.3.0'
